# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_FRAME_BOOST) += frame_info.o
obj-$(CONFIG_OPLUS_FEATURE_FRAME_BOOST) += cluster_boost.o
obj-$(CONFIG_OPLUS_FEATURE_FRAME_BOOST) += frame_boost.o
obj-$(CONFIG_OPLUS_FEATURE_FRAME_BOOST) += frame_debug.o
obj-$(CONFIG_OPLUS_FEATURE_FRAME_BOOST) += frame_group.o
