# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_OPLUS_CHG_CORE)		+= oplus_chg_core.o
obj-$(CONFIG_OPLUS_CHARGER)		+= oplus_charger.o
obj-$(CONFIG_OPLUS_CHG_VOTER)		+= oplus_chg_voter.o
obj-$(CONFIG_OPLUS_CHG_OPS_MANAGER)	+= oplus_chg_ops_manager.o
obj-$(CONFIG_OPLUS_CHG_COMM)		+= oplus_chg_comm.o
obj-$(CONFIG_OPLUS_CHG_CONFIGFS)	+= oplus_configfs.o
obj-$(CONFIG_OPLUS_CHG_DEBUG)		+= oplus_debug_info.o

obj-y += charger_ic/
obj-y += gauge_ic/