/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * OPLUS/Qualcomm extended power_supply_property values
 * Extracted from 4.19 include/linux/power_supply.h
 * Inserted after upstream POWER_SUPPLY_PROP_SERIAL_NUMBER
 */

#ifndef __OPLUS_POWER_SUPPLY_EXT_H__
#define __OPLUS_POWER_SUPPLY_EXT_H__

/*
 * These enum values extend enum power_supply_property from
 * include/linux/power_supply.h. They begin after the last upstream value
 * (POWER_SUPPLY_PROP_SERIAL_NUMBER).
 *
 * NOTE: These must match the values used in the OPLUS charging framework.
 * For the QG driver, we only need a subset, but we define them all for
 * consistency with the 4.19 codebase.
 */
enum oplus_power_supply_ext_property {
	/* Begin after POWER_SUPPLY_PROP_SERIAL_NUMBER */
	OPLUS_POWER_SUPPLY_PROP_BASE = 0,

	/* Properties of type `int' */
	POWER_SUPPLY_PROP_RESISTANCE = (OPLUS_POWER_SUPPLY_PROP_BASE + 100),
	POWER_SUPPLY_PROP_RESISTANCE_CAPACITIVE,
	POWER_SUPPLY_PROP_RESISTANCE_ID,		/* in Ohms */
	POWER_SUPPLY_PROP_RESISTANCE_NOW,
	POWER_SUPPLY_PROP_CURRENT_QNOVO,
	POWER_SUPPLY_PROP_VOLTAGE_QNOVO,
	POWER_SUPPLY_PROP_CURRENT_CAPACITY,
	POWER_SUPPLY_PROP_SOH,				/* State of Health */
	POWER_SUPPLY_PROP_ESR_ACTUAL,
	POWER_SUPPLY_PROP_ESR_NOMINAL,
	POWER_SUPPLY_PROP_FG_TYPE,
	POWER_SUPPLY_PROP_FG_RESET,
	POWER_SUPPLY_PROP_BATT_AGE_LEVEL,
	POWER_SUPPLY_PROP_BATTERY_TYPE,
	POWER_SUPPLY_PROP_CYCLE_COUNTS,
	/* POWER_SUPPLY_PROP_CHARGE_FULL already defined in 5.10 power_supply.h */
	POWER_SUPPLY_PROP_CC_SOC,
	POWER_SUPPLY_PROP_VOLTAGE_VPH,
	POWER_SUPPLY_PROP_CHIP_VERSION,
	POWER_SUPPLY_PROP_REAL_CAPACITY,
	POWER_SUPPLY_PROP_CAPACITY_RAW,
	POWER_SUPPLY_PROP_SOC_REPORTING_READY,
	POWER_SUPPLY_PROP_DEBUG_BATTERY,
	POWER_SUPPLY_PROP_RECHARGE_SOC,
	POWER_SUPPLY_PROP_SCALE_MODE_EN,
	POWER_SUPPLY_PROP_CHARGE_DONE,
	POWER_SUPPLY_PROP_FORCE_RECHARGE,
	POWER_SUPPLY_PROP_FG_RESET_CLOCK,
	POWER_SUPPLY_PROP_PARALLEL_DISABLE,
	POWER_SUPPLY_PROP_PARALLEL_MODE,
	POWER_SUPPLY_PROP_PARALLEL_BATFET_MODE,
	POWER_SUPPLY_PROP_PARALLEL_FCC_MAX,
	POWER_SUPPLY_PROP_PARALLEL_OUTPUT_MODE,
	POWER_SUPPLY_PROP_PARALLEL_CURRENT_NOW,
	POWER_SUPPLY_PROP_BATT_PROFILE_VERSION,
	POWER_SUPPLY_PROP_BATT_FULL_CURRENT,
	POWER_SUPPLY_PROP_BATT_FULL_CHARGE,
	POWER_SUPPLY_PROP_CHARGING_ENABLED,
};

#endif /* __OPLUS_POWER_SUPPLY_EXT_H__ */
