# SPDX-License-Identifier: GPL-2.0-only
#
# OPLUS (OnePlus/Oppo/Realme) SoC-specific drivers
#

obj-$(CONFIG_OPLUS_PROJECT_INFO)	+= oplus_project.o
obj-$(CONFIG_OPLUS_DEVICE_INFO)		+= device_info.o
obj-$(CONFIG_OPLUS_BOOT_MODE)		+= boot_mode.o
obj-$(CONFIG_OPLUS_HEALTHINFO)		+= healthinfo/
